binaries=generator checker solver brute_slow brute_fast random

# if using custom grader
# binaries+=grader

BASE_PATH=$(shell git rev-parse --show-toplevel)

include $(BASE_PATH)/common/Makefile.include

