binaries=generator checker grader solver brute_1 brute_2 brute_3 random distinct atli_slow atli_fast max2 max3

BASE_PATH=$(shell git rev-parse --show-toplevel)

include $(BASE_PATH)/common/Makefile.include

