binaries=generator checker solver sols/brute1 sols/wa-max

# if using custom grader
# binaries+=grader

BASE_PATH=$(shell git rev-parse --show-toplevel)

include $(BASE_PATH)/common/Makefile.include

