binaries=generator checker solver
binaries+=sols/brute1 sols/brute2 sols/wa-max sols/antti100

# if using custom grader
# binaries+=grader

BASE_PATH=$(shell git rev-parse --show-toplevel)

include $(BASE_PATH)/common/Makefile.include

